# Generated by Django 3.1.2 on 2020-11-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0002_profiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hood',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='infodesk.neighbourhoods'),
        ),
    ]
