# Generated by Django 3.1.2 on 2020-11-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0003_auto_20201103_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hood',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='infodesk.neighbourhoods'),
        ),
    ]
