# Generated by Django 3.1.2 on 2020-11-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0004_auto_20201104_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hood',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
