# Generated by Django 3.1.2 on 2020-11-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infodesk', '0006_auto_20201104_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hood',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='infodesk.neighbourhoods'),
        ),
    ]
